name: DevOps-CI-CD-Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 - Get my code
        uses: actions/checkout@v3

      - name: Step 2 - Build portfolio website
        run: docker build -t portfolio-website ./portfolio-project

      - name: Step 3 - Check Docker image
        run: docker images

      - name: Step 4 - Pipeline complete
        run: echo "Portfolio website built successfully!"
