name: DevOps-CI-CD-Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 - Get my code
        uses: actions/checkout@v3

      - name: Step 2 - Build portfolio website
        run: docker build -t portfolio-website ./portfolio-project

      - name: Step 3 - Build final DevOps app
        run: docker build -t devops-final-app ./devops-final-project

      - name: Step 4 - Check all Docker images
        run: docker images

      - name: Step 5 - Pipeline complete
        run: echo "All projects built successfully!"
